const P={windows:{name:'Windows',tag:'WIN',color:'#78aef6',info:'Workstation, local lab and Windows-service administration.'},rhel:{name:'RHEL / Linux',tag:'RHEL',color:'#b4eb85',info:'Production database-host administration on RHEL.'}};
const R=[
['windows','Connection','Oracle client','Connect from Windows to Oracle','PowerShell or Command Prompt','sqlplus <user>@//<linux-host>:1521/<service_name>','Use the PDB service name where applicable. SQL*Plus prompts for the password.','SHOW USER\nSHOW CON_NAME'],
['windows','Connection','PostgreSQL 18.4','Connect to the Windows PostgreSQL service','PowerShell','& "C:\\app\\postgresql\\postgresql-18.4\\pgsql\\bin\\psql.exe" `\n  -h localhost -p 5432 -U postgres -d postgres -W','Your lab binaries are under C:\\app\\postgresql\\postgresql-18.4\\pgsql. The service is pgsql18.4.','SELECT version(), current_database(), current_user;'],
['windows','Connection','MySQL','Connect to a MySQL server','PowerShell or Command Prompt','mysql -h <host> -P 3306 -u <user> -p -D <database>','Uppercase -P is the port. The account is identified by username and client host.','SELECT @@hostname, @@port, DATABASE(), CURRENT_USER();'],
['windows','Connection','MongoDB','Connect to MongoDB from Windows','PowerShell','mongosh "mongodb://<host>:27017/<database>" `\n  --username <user> --authenticationDatabase <auth_db> --password','auth_db is where the user was created; it can differ from the target database.','db.getName()\ndb.hello()'],
['windows','Services & logs','PostgreSQL 18.4','Check the PostgreSQL Windows service','PowerShell as Administrator','Get-Service pgsql18.4\nsc.exe qc pgsql18.4\nGet-WinEvent -LogName Application -MaxEvents 30','Confirm service state and configured binary/data paths before changing anything.','Service status is Running; then test psql locally.'],
['windows','Services & logs','MySQL / MongoDB','Check services and listening ports','PowerShell as Administrator','Get-Service *mysql*, *mongo*\nGet-NetTCPConnection -State Listen |\n  Where-Object LocalPort -in 3306,27017','Service names vary by installation. Check the listener and a client login separately.','Confirm PID, service state and expected port.'],
['windows','Network first','Any remote database','Check DNS and TCP before login troubleshooting','PowerShell','Resolve-DnsName <host>\nTest-NetConnection <host> -Port <port>','Start here when a remote connection fails. A TCP failure points to DNS, routing, firewall or listener state.','1521 Oracle · 5432 PostgreSQL · 3306 MySQL · 27017 MongoDB'],
['rhel','Connection','Oracle 19c','Connect locally as the Oracle software owner','RHEL shell','export ORACLE_SID=<sid>\nsqlplus / as sysdba\nSELECT instance_name, host_name, status FROM v$instance;\nSHOW CON_NAME','Set ORACLE_HOME and ORACLE_SID for the intended instance. Confirm PDB/container before administration.','Check instance status, database role and current container.'],
['rhel','Connection','PostgreSQL','Connect locally as postgres','RHEL shell','sudo -u postgres psql -d postgres\nSELECT version(), current_database(), current_user;\nSHOW data_directory;','A local connection normally uses a Unix socket and still follows pg_hba.conf rules.','Confirm data directory, database and current role.'],
['rhel','Connection','MySQL','Connect using the configured socket','RHEL shell','mysql --socket=/run/mysqld/mysql.sock -u <admin> -p\nSELECT @@hostname, @@socket, @@datadir;','Your RHEL MySQL target uses /run/mysqld/mysql.sock and /data/mysql.','Confirm hostname, socket and datadir.'],
['rhel','Connection','MongoDB','Connect locally and check replica topology','RHEL shell','mongosh "mongodb://localhost:27017/admin" --username <admin> --password\ndb.hello()\nrs.status()','rs.status() applies to a replica set. Include TLS and replica-set settings when connecting remotely.','Confirm primary, healthy members and replica-set name.'],
['rhel','Services & logs','Oracle 19c','Check Oracle listener and diagnostic location','RHEL shell / SQL*Plus','lsnrctl status\nsqlplus / as sysdba\nSELECT name, value FROM v$diag_info\nWHERE name IN (\'Diag Trace\',\'Default Trace File\');','Database and listener availability are separate checks.','Check registered services, listener address and matching alert-log timestamp.'],
['rhel','Services & logs','PostgreSQL','Check PostgreSQL service and logs','RHEL shell','systemctl status postgresql\njournalctl -u postgresql --since "30 minutes ago"\npg_isready -h <host> -p 5432','The unit name can be versioned by the package. Discover the actual unit before restart.','A ready response and SQL connection test.'],
['rhel','Services & logs','MySQL','Check MySQL service and error log','RHEL shell','systemctl status mysqld\njournalctl -u mysqld --since "30 minutes ago"\nmysqladmin --socket=/run/mysqld/mysql.sock -u <admin> -p ping','mysqld is the usual RHEL service name. Check the configured error log too.','Ping, SQL login, error log and filesystem capacity.'],
['rhel','Services & logs','MongoDB','Check MongoDB service and log','RHEL shell','systemctl status mongod\njournalctl -u mongod --since "30 minutes ago"\nss -lntp | grep 27017','For replica-set maintenance, use a rolling plan and preserve majority availability.','mongod process, port, db.hello() and member health.'],
['rhel','Host readiness','RHEL database host','Check CPU, memory, disk and network basics','RHEL shell','hostname -f\nfree -h\nvmstat 1 5\ndf -hT\nlsblk\ngetent hosts <remote-host>\nnc -vz <remote-host> <port>','For Oracle also validate HugePages, THP=never, memlock and the SGA/PGA plan.','No filesystem pressure, no active swapping, correct DNS and TCP path.'],
['rhel','Security & access','RHEL database host','Confirm account and file ownership context','RHEL shell','id\nps -ef | egrep "ora_pmon|postgres|mysqld|mongod"\nnamei -l <data-path>','Run database commands as the correct OS account. Verify owner and directory path first.','Match the software owner and least-privilege OS groups.']
];
let platform='windows',group='All platform tasks',query='';const $=s=>document.querySelector(s),groups=['All platform tasks','Connection','Services & logs','Network first','Host readiness','Security & access'];
const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
function box(code,where,id){return `<div class="terminal"><div class="terminal-bar"><span>${esc(where)}</span><button data-copy="${id}">Copy</button></div><pre><code>${esc(code)}</code></pre></div>`}
function render(){const p=P[platform],found=R.filter(r=>r[0]===platform&&(group==='All platform tasks'||r[1]===group)&&r.join(' ').toLowerCase().includes(query));document.documentElement.style.setProperty('--engine',p.color);$('#engineTabs').innerHTML=Object.entries(P).map(([k,v])=>`<button class="engine ${platform===k?'selected':''}" data-platform="${k}"><span class="engine-icon" style="color:${v.color}">${v.tag}</span><span><strong>${v.name}</strong><small>${v.info}</small></span></button>`).join('');$('#categories').innerHTML=groups.map((g,i)=>`<button class="nav-item ${group===g?'active':''}" data-group="${g}"><span>${['▦','⌁','⚙','⌘','▤','◇'][i]}</span>${g}</button>`).join('');$('#engineName').textContent=p.name.toUpperCase()+' PLATFORM';$('#model').textContent=p.info;$('#tip').textContent=platform==='windows'?'Start with PowerShell service and network checks, then use the appropriate database client.':'Start with the correct database OS account, host health, systemd and journalctl.';$('#docs').hidden=true;$('#sectionTitle').textContent=group;$('#resultCount').textContent=`${found.length} procedures`;$('#cards').className='cards';$('#cards').innerHTML=found.length?found.map(r=>{const id=R.indexOf(r);return `<article class="procedure"><div class="card-top"><span class="eyebrow" style="color:${p.color}">${r[2]} · ${r[1]}</span><span class="badge read">${p.name}</span></div><h3>${r[3]}</h3><p>${r[6]}</p>${box(r[5],r[4],id)}<div class="verify"><span>✓</span><div><strong>What to verify</strong><p>${r[7]}</p></div></div></article>`}).join(''):'<div class="empty"><h3>No matching procedures</h3><p>Try a service name, database or command.</p></div>'}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.platform){platform=b.dataset.platform;group='All platform tasks';render()}if(b.dataset.group){group=b.dataset.group;render()}if(b.dataset.copy!==undefined){try{await navigator.clipboard.writeText(R[+b.dataset.copy][5]);b.textContent='Copied';setTimeout(()=>b.textContent='Copy',1400)}catch{b.textContent='Select text'}}if(b.id==='compare')$('#comparison').showModal();if(b.id==='closeDialog')$('#comparison').close()});$('#search').addEventListener('input',e=>{query=e.target.value.toLowerCase();render()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();$('#search').focus()}});render();
