const engines={oracle:{name:'Oracle',version:'19c',color:'#e7645c',short:'OR',model:'Instance → database → schema',tip:'An Oracle user owns a schema. For multitenant databases, confirm the current container before administration.',docs:'https://docs.oracle.com/en/database/oracle/oracle-database/19/'},postgres:{name:'PostgreSQL',version:'16–18',color:'#76aaf5',short:'PG',model:'Cluster → database → schema',tip:'A PostgreSQL cluster is a data directory managed by one server instance. Roles are shared across its databases.',docs:'https://www.postgresql.org/docs/18/'},mysql:{name:'MySQL',version:'8.0 / 8.4',color:'#e8ad61',short:'MY',model:'Server → database (= schema)',tip:'MySQL accounts are identified by both user and host. A database and a schema mean the same thing.',docs:'https://dev.mysql.com/doc/refman/8.0/en/'},mongo:{name:'MongoDB',version:'mongosh · self-managed',color:'#74cfa3',short:'MG',model:'Replica set → database → collection',tip:'A replica set provides redundancy. A database contains collections of documents; users belong to an authentication database.',docs:'https://www.mongodb.com/docs/manual/'}};
const rows=[];function add(e,c,t,where,code,why,check,risk='Read only'){rows.push({e,c,t,where,code,why,check,risk})}
add('oracle','Connect & identify','Connect and confirm your instance','Linux shell → SQL*Plus',`sqlplus / as sysdba\nSELECT instance_name, host_name, version, status FROM v$instance;\nSELECT name, open_mode, database_role FROM v$database;\nSHOW CON_NAME`, 'Use the Oracle software owner with OS authentication. Set the correct ORACLE_HOME and ORACLE_SID first.','Confirm host, database role and container before any change.');
add('oracle','Setup & configuration','Inspect memory and file locations','SQL*Plus',`SHOW PARAMETER spfile\nSHOW PARAMETER sga_target\nSHOW PARAMETER pga_aggregate_target\nSHOW PARAMETER diagnostic_dest\nSELECT name FROM v$controlfile;`, 'Locate active configuration and memory targets before tuning.','An empty spfile value indicates startup from a text parameter file.');
add('oracle','Service control','Start or stop a standalone instance','SQL*Plus · SYSDBA',`-- Start a stopped standalone instance\nSTARTUP;\n-- Alternative: planned shutdown\nSHUTDOWN IMMEDIATE;`, 'Choose one action. Shutdown immediate disconnects sessions and rolls back uncommitted work. For Oracle Restart or RAC, use the configured srvctl workflow.','After startup, check v$instance and v$database; verify required PDBs are open.','Service impact');
add('oracle','Service control','Check listener and registered services','Linux shell',`lsnrctl status\nlsnrctl services`, 'Listener availability and database availability are separate checks.','Confirm the expected listening address and service handlers.');
add('oracle','Users & access','Inspect accounts and grants','SQL · DBA privileges',`SELECT username, account_status, default_tablespace\nFROM dba_users ORDER BY username;\nSELECT granted_role FROM dba_role_privs\nWHERE grantee = 'APP_USER';\nSELECT privilege FROM dba_sys_privs\nWHERE grantee = 'APP_USER';`, 'Review account state, roles and system privileges in the intended container.','Object grants require a separate review of dba_tab_privs.');
add('oracle','Users & access','Create a least-privilege local account','SQL · target PDB',`CREATE USER app_reader IDENTIFIED BY "<strong-password>";\nGRANT CREATE SESSION TO app_reader;\nGRANT SELECT ON app_owner.example_table TO app_reader;`, 'Replace placeholders. Connect to the target PDB first; this is a local application account example.','Review dba_users and dba_tab_privs, then test with the new account.','Changes access');
add('oracle','Monitoring','Find active sessions and blockers','SQL · catalog access',`SELECT sid, serial#, username, status, event,\n       blocking_session, sql_id\nFROM v$session\nWHERE type = 'USER' AND status = 'ACTIVE';`, 'Start with waits and blocking evidence. This query does not require AWR or ASH.','Correlate SQL ID, application and duration before intervention.');
add('oracle','Storage & maintenance','Review allocated and free tablespace space','SQL · catalog access',`SELECT tablespace_name, ROUND(SUM(bytes)/POWER(1024,3),2) allocated_gb\nFROM dba_data_files GROUP BY tablespace_name;\nSELECT tablespace_name, ROUND(SUM(bytes)/POWER(1024,3),2) free_gb\nFROM dba_free_space GROUP BY tablespace_name;`, 'Allocated size and free extents are different measures. These views cover permanent tablespaces.','Also check filesystem/ASM capacity and autoextend MAXBYTES; TEMP needs separate inspection.');
add('oracle','Troubleshooting','Locate the diagnostic logs','SQL · catalog access',`SELECT name, value FROM v$diag_info\nWHERE name IN ('Diag Trace','Diag Alert','Default Trace File');`, 'Use the trace directory for the text alert log; Diag Alert identifies the XML alert directory.','Match error timestamps to the incident. Check edition and license entitlement before using AWR, ASH or tuning packs.');
add('postgres','Connect & identify','Connect and identify the cluster','Shell → psql',`psql -h <host> -p 5432 -U <admin> -d postgres\nSELECT version(), current_database(), current_user;\nSELECT inet_server_addr(), inet_server_port();\nSHOW data_directory;`, 'psql is the client; postgres is the server. Local socket connections can return NULL for the network address.','Confirm database, port and data directory.');
add('postgres','Setup & configuration','Initialize a new cluster','Linux shell · postgres OS user',`initdb -D /data/pgdata --encoding=UTF8 --auth=scram-sha-256 --pwprompt`, 'Use a new empty directory owned by postgres and binaries matching the intended version. This creates a cluster, not a replica set.','Review postgresql.conf and pg_hba.conf before allowing network access. Never initialize an existing data directory.','New setup');
add('postgres','Setup & configuration','Locate active configuration','psql',`SHOW config_file;\nSHOW hba_file;\nSHOW data_directory;\nSHOW listen_addresses;\nSHOW port;\nSELECT name, setting, pending_restart\nFROM pg_settings WHERE pending_restart;`, 'Configuration can live outside the data directory, depending on packaging.','pg_hba.conf rules are evaluated in order; confirm the matching rule.');
add('postgres','Service control','Control a manually managed cluster','Linux shell · postgres OS user',`pg_ctl -D /data/pgdata status\n# Choose the required action:\npg_ctl -D /data/pgdata -l /data/pgdata/server.log start\npg_ctl -D /data/pgdata -m fast stop`, 'Fast stop disconnects clients and rolls back active transactions. If systemd owns the service, use its actual unit instead of mixing control methods.','Run pg_isready -h <host> -p 5432 and then a SQL connection check.','Service impact');
add('postgres','Users & access','Review roles and database privileges','psql',`\\du\n\\l+\n\\dn+\n\\dp`, 'psql backslash commands show roles, databases, schemas and object permissions.','Roles are cluster-wide; schema and object grants are database-specific.');
add('postgres','Users & access','Create a read-only role','psql · privileged administrator',`CREATE ROLE app_reader LOGIN;\n\\password app_reader\nGRANT CONNECT ON DATABASE appdb TO app_reader;\n-- Connect to appdb before the following grants\n\\connect appdb\nGRANT USAGE ON SCHEMA public TO app_reader;\nGRANT SELECT ON ALL TABLES IN SCHEMA public TO app_reader;`, 'The password prompt avoids a clear-text password in command history. Grants cover existing tables only.','For future tables, configure ALTER DEFAULT PRIVILEGES for each actual object owner.','Changes access');
add('postgres','Monitoring','Find active queries and blockers','SQL · pg_read_all_stats or admin',`SELECT pid, usename, state, wait_event_type, wait_event,\n       now() - query_start AS duration,\n       pg_blocking_pids(pid) AS blockers, query\nFROM pg_stat_activity\nWHERE state <> 'idle' AND pid <> pg_backend_pid()\nORDER BY query_start;`, 'Duration is elapsed time since query start. Other users’ query details require appropriate privileges.','Look for long transactions and blocking chains before considering cancellation.');
add('postgres','Storage & maintenance','Review sizes and vacuum activity','SQL',`SELECT datname, pg_size_pretty(pg_database_size(datname))\nFROM pg_database ORDER BY pg_database_size(datname) DESC;\nSELECT schemaname, relname, n_dead_tup, last_autovacuum\nFROM pg_stat_user_tables ORDER BY n_dead_tup DESC LIMIT 20;`, 'Dead tuple counts are estimates. Autovacuum is part of normal PostgreSQL operations.','Investigate long transactions and autovacuum settings; do not jump straight to VACUUM FULL.');
add('postgres','Troubleshooting','Check standby role and streaming','SQL · monitoring privileges',`SELECT pg_is_in_recovery();\n-- On the primary:\nSELECT application_name, client_addr, state, sync_state,\n       write_lag, flush_lag, replay_lag\nFROM pg_stat_replication;`, 'pg_is_in_recovery is true on a physical standby. Replication lag fields are not a simple backlog timer.','An idle system may show NULL lag; verify WAL positions and receiver status as needed.');
add('mysql','Connect & identify','Connect and identify the server','Shell → mysql',`mysql -h <host> -P 3306 -u <admin> -p\nSELECT VERSION(), @@hostname, @@port, @@server_uuid;\nSELECT USER(), CURRENT_USER(), DATABASE();`, 'Use the password prompt. CURRENT_USER shows the account used for privilege checks.','Confirm the host and account host-pattern before making changes.');
add('mysql','Setup & configuration','Inspect active paths and key settings','mysql',`SHOW VARIABLES WHERE Variable_name IN\n('datadir','socket','port','log_error','server_id',\n 'innodb_buffer_pool_size','max_connections');`, 'The running server is the best source of effective settings. Option file locations vary by installation.','Use mysqld --verbose --help to inspect default option-file search paths.');
add('mysql','Service control','Check server and Linux service','Linux shell',`mysqladmin -h <host> -u <admin> -p ping\nsystemctl status mysqld\njournalctl -u mysqld --since '30 minutes ago'`, 'mysqld is a common RHEL unit name; other packages may use mysql. Discover the actual unit on your host.','Ping confirms a responding server; a successful SQL login separately verifies access.');
add('mysql','Service control','Restart the managed service','Linux shell · sudo',`sudo systemctl restart mysqld\nsystemctl status mysqld`, 'Use the actual installed service name during an approved maintenance window. Restart disconnects clients.','Check the error log and application connectivity after restart.','Service impact');
add('mysql','Users & access','Inspect accounts and grants','mysql · administrative account',`SELECT user, host, account_locked FROM mysql.user;\nSHOW GRANTS FOR 'app_reader'@'10.0.0.25';`, 'The same username with another host is a different account. Replace the host with the actual account entry.','Review authentication, host scope and object privileges together.');
add('mysql','Users & access','Create a read-only application account','mysql · account administration privileges',`CREATE USER 'app_reader'@'10.0.0.25'\nIDENTIFIED BY '<strong-password>';\nGRANT SELECT ON appdb.* TO 'app_reader'@'10.0.0.25';\nSHOW GRANTS FOR 'app_reader'@'10.0.0.25';`, 'Replace the example IP, password and database. SQL account statements do not require FLUSH PRIVILEGES.','Test from the intended client host.','Changes access');
add('mysql','Monitoring','Inspect activity and InnoDB waits','mysql · monitoring privileges',`SHOW FULL PROCESSLIST;\nSELECT * FROM performance_schema.data_lock_waits;\nSHOW ENGINE INNODB STATUS\\G`, 'PROCESS privilege is needed to see other users’ threads. InnoDB status includes recent deadlock information.','Correlate waiting transactions and application requests before killing a connection.');
add('mysql','Storage & maintenance','Estimate database sizes','mysql',`SELECT table_schema,\n ROUND(SUM(data_length+index_length)/POWER(1024,3),2) AS estimated_gb\nFROM information_schema.tables\nGROUP BY table_schema ORDER BY estimated_gb DESC;`, 'InnoDB metadata sizes are estimates and do not represent all filesystem usage.','Check binary logs, undo, temporary files and filesystem capacity separately.');
add('mysql','Troubleshooting','Inspect replica health','mysql · REPLICATION CLIENT',`SHOW REPLICA STATUS\\G`, 'Supported in MySQL 8.0.22+ and 8.4. Run on the replica; an empty result means no configured replication channel is shown.','Check both running threads, last errors and replication positions; Seconds_Behind_Source alone is insufficient.');
add('mongo','Connect & identify','Connect and confirm topology','Shell → mongosh',`mongosh 'mongodb://<host>:27017/admin' --username <admin> --password\ndb.version()\ndb.getName()\ndb.hello()`, 'The URI selects the authentication database in this example. Use the deployed TLS and replica-set connection options.','Confirm setName and isWritablePrimary before administration.');
add('mongo','Setup & configuration','Inspect startup configuration','mongosh · admin privileges',`db.adminCommand({ getCmdLineOpts: 1 })`, 'Shows parsed startup options, including configured storage and replication settings.','Check storage.dbPath, net.bindIp, port, authorization and replica set name.');
add('mongo','Service control','Inspect the Linux service and log','Linux shell',`systemctl status mongod\njournalctl -u mongod --since '30 minutes ago'`, 'mongod is the usual package service. MongoDB may write its main log to a configured file rather than journald.','Read systemLog.path from the configuration and inspect the matching log.');
add('mongo','Service control','Restart a standalone service','Linux shell · sudo',`sudo systemctl restart mongod\nsystemctl status mongod`, 'This example is for a standalone server. Replica sets need a topology-aware rolling maintenance plan and majority availability checks.','Reconnect and inspect db.hello() and logs.','Service impact');
add('mongo','Users & access','Review users in the current database','mongosh · user administration privileges',`use admin\ndb.getUsers()`, 'MongoDB users are scoped to an authentication database, while their roles can cover other databases.','Repeat in the application authentication database if users were created there.');
add('mongo','Users & access','Create an application read-only user','mongosh · user administration privileges',`use appdb\ndb.createUser({\n  user: "app_reader",\n  pwd: passwordPrompt(),\n  roles: [{ role: "read", db: "appdb" }]\n})`, 'Use authSource=appdb when connecting as this user. Authentication must already be enabled on the deployment.','Test a read operation as the new user.','Changes access');
add('mongo','Monitoring','Inspect connections and replica members','mongosh · monitoring privileges',`db.serverStatus().connections\nrs.status().members.map(m => ({\n  name: m.name, state: m.stateStr,\n  health: m.health, optimeDate: m.optimeDate\n}))`, 'The replica-set portion requires a replica set. Member heartbeat state is a point-in-time observation.','Confirm a primary, expected secondaries and healthy replication progress.');
add('mongo','Storage & maintenance','Inspect database and collection sizes','mongosh',`use appdb\ndb.stats(1024 * 1024)\ndb.runCommand({ collStats: "example_collection", scale: 1048576 })`, 'Replace the collection name. The scale reports applicable size fields in MiB; logical data and allocated storage differ.','Also check filesystem capacity and WiredTiger cache pressure.');
add('mongo','Troubleshooting','Review feature compatibility and set config','mongosh · admin privileges',`db.adminCommand({ getParameter: 1, featureCompatibilityVersion: 1 })\nrs.conf()`, 'Server binary version and feature compatibility version are separate. rs.conf requires a replica set.','Before an upgrade, follow the exact source-to-target version guide and confirm every member’s binary version.');
const connections={oracle:{client:'SQL*Plus',port:'1521',command:'sqlplus <user>@//<host>:1521/<service_name>',check:"SHOW USER\nSHOW CON_NAME\nSELECT sys_context('USERENV','SERVER_HOST') FROM dual;",note:'Use the service name, including the PDB service when applicable. SQL*Plus prompts for the password.',local:'sqlplus / as sysdba',localNote:'On the database server, with OSDBA membership and the correct ORACLE_HOME / ORACLE_SID.',docs:'https://docs.oracle.com/en/database/oracle/oracle-database/19/sqpug/starting-SQL-Plus.html'},postgres:{client:'psql',port:'5432',command:'psql -h <host> -p 5432 -U <user> -d <database> -W',check:'\\conninfo\nSELECT current_database(), current_user;',note:'Uppercase -U selects the user; lowercase -p selects the port. -W prompts for the password.',local:'sudo -u postgres psql -d postgres',localNote:'Typical Linux socket connection with peer authentication. Requires sudo access and a matching pg_hba.conf rule.',docs:'https://www.postgresql.org/docs/18/app-psql.html'},mysql:{client:'mysql',port:'3306',command:'mysql -h <host> -P 3306 -u <user> -p -D <database>',check:'SELECT @@hostname, @@port, DATABASE(), CURRENT_USER();',note:'Uppercase -P is the port; lowercase -p prompts for the password. User and client host identify the account.',local:'mysql -u <user> -p',localNote:'Uses the default local connection settings; on Unix this is usually a socket. Account authentication still applies.',docs:'https://dev.mysql.com/doc/refman/8.0/en/connecting.html'},mongo:{client:'mongosh',port:'27017',command:'mongosh "mongodb://<host>:27017/<database>" --username <user> --authenticationDatabase <auth_db> --password',check:'db.getName()\ndb.hello()',note:'auth_db is where the user was created, which may differ from the target database. Keep --password last for the prompt.',local:'mongosh "mongodb://localhost:27017/<database>" --username <user> --authenticationDatabase <auth_db> --password',localNote:'Uses the same authentication model as a remote connection. Add the deployed TLS and replica-set options when required.',docs:'https://www.mongodb.com/docs/mongodb-shell/connect/'}};
let engine='all',category='Connect & identify',query='';const cats=['All procedures',...new Set(rows.map(x=>x.c))];const $=s=>document.querySelector(s);function esc(v){return String(v).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function terminal(code,label,copy){return `<div class="terminal"><div class="terminal-bar"><span>${esc(label)}</span><button data-clip="${copy}">Copy</button></div><pre><code>${esc(code)}</code></pre></div>`}
function render(){const all=engine==='all',e=all?null:engines[engine];document.documentElement.style.setProperty('--engine',all?'#b4eb85':e.color);$('#engineTabs').innerHTML=`<button class="engine ${all?'selected':''}" data-engine="all" aria-pressed="${all}"><span class="engine-icon">⇄</span><span><strong>All databases</strong><small>Side by side</small></span></button>`+Object.entries(engines).map(([k,v])=>`<button class="engine ${k===engine?'selected':''}" data-engine="${k}" aria-pressed="${k===engine}"><span class="engine-icon" style="color:${v.color}">${v.short}</span><span><strong>${v.name}</strong><small>${v.version}</small></span></button>`).join('');$('#categories').innerHTML=cats.map((c,i)=>`<button class="nav-item ${category===c?'active':''}" data-cat="${c}"><span>${['▦','⌁','⚙','◷','♙','▥','▤','◇'][i]}</span>${c==='Connect & identify'?'Connect to database':c}</button>`).join('');$('.engine-info').hidden=all||category==='Connect & identify';if(e){$('#engineName').textContent=e.name;$('#model').textContent=e.model;$('#tip').textContent=e.tip;$('#docs').href=e.docs}$('#sectionTitle').textContent=category==='Connect & identify'?'Connect to database':category;
if(category==='Connect & identify'){const keys=Object.keys(connections).filter(k=>(all||k===engine)&&[engines[k].name,...Object.values(connections[k])].join(' ').toLowerCase().includes(query));$('#resultCount').textContent=`${keys.length} databases`;$('#cards').className='connection-grid';$('#cards').innerHTML=keys.map(k=>{const v=engines[k],c=connections[k];return `<article class="connection-card" style="--card-engine:${v.color}"><div class="connection-heading"><span class="engine-icon" style="color:${v.color}">${v.short}</span><div><h3>${v.name}</h3><span>${c.client} · default port ${c.port}</span></div></div><h4>Remote connection</h4>${terminal(c.command,'Run in your terminal',k+':command')}<p>${c.note}</p><details><summary>Local connection</summary>${terminal(c.local,'On the database host',k+':local')}<p>${c.localNote}</p></details><h4>Confirm the connection</h4>${terminal(c.check,'Inside '+c.client,k+':check')}<a class="connection-doc" href="${c.docs}" target="_blank" rel="noopener noreferrer">Connection documentation ↗</a></article>`}).join('');if(!keys.length)$('#cards').innerHTML=empty();return}
const found=rows.filter(r=>(all||r.e===engine)&&(category==='All procedures'||r.c===category)&&[engines[r.e].name,r.t,r.code,r.why,r.c,r.check].join(' ').toLowerCase().includes(query));$('#resultCount').textContent=`${found.length} procedures`;$('#cards').className='cards';$('#cards').innerHTML=found.length?found.map(r=>{const id=rows.indexOf(r);return `<article class="procedure"><div class="card-top"><span class="eyebrow" style="color:${engines[r.e].color}">${engines[r.e].name} · ${r.c}</span><span class="badge ${r.risk==='Read only'?'read':'change'}">${r.risk}</span></div><h3>${r.t}</h3><p>${r.why}</p>${terminal(r.code,r.where,'row:'+id)}<div class="verify"><span>✓</span><div><strong>What to verify</strong><p>${r.check}</p></div></div></article>`}).join(''):empty()}
function empty(){return '<div class="empty"><h3>No matching procedures</h3><p>Try a database name, command or task.</p><button id="reset">Clear filters</button></div>'}
document.addEventListener('click',async ev=>{const el=ev.target.closest('button');if(!el)return;if(el.dataset.engine){engine=el.dataset.engine;render()}if(el.dataset.cat){category=el.dataset.cat;render()}if(el.dataset.clip){const [key,field]=el.dataset.clip.split(':');const code=key==='row'?rows[Number(field)].code:connections[key][field];try{await navigator.clipboard.writeText(code);el.textContent='Copied';setTimeout(()=>el.textContent='Copy',1600)}catch{el.textContent='Select text to copy'}}if(el.id==='reset'){query='';engine='all';$('#search').value='';render()}if(el.id==='compare')$('#comparison').showModal();if(el.id==='closeDialog')$('#comparison').close()});$('#search').addEventListener('input',ev=>{query=ev.target.value.toLowerCase();render()});document.addEventListener('keydown',ev=>{if((ev.ctrlKey||ev.metaKey)&&ev.key==='k'){ev.preventDefault();$('#search').focus()}});render();
